# Generated by Django 5.1.6 on 2025-03-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
    ]
