# Generated by Django 5.1.6 on 2025-02-20 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0001_initial'),
        ('projects', '0003_alter_project_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectreview',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='projects.project'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
