"""
Django settings for freelancefusionbackendserver project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from django.conf import settings
from pathlib import Path
from datetime import timedelta
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q1y-$*1*rwqaqwc1(plcu*t8h0soumf*@rte1p%-%m!z!hh_+3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'admin_material.apps.AdminMaterialDashboardConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    #install packages
    
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
     'drf_yasg',
     'khalti',
     'django_filters',
    
    
    
    #my apps
    'account',
    'projectcategories',
    'projects',
    'applications',
    'contracts',
    'payments',
    'project_review',
    'chat',
    'notifications',
    'organization_setting',
    
    
    
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'freelancefusionbackendserver.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
       'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Add this line
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'freelancefusionbackendserver.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',       # Replace with your actual DB name
        'USER': 'postgres',         # Replace with your PostgreSQL username
        'PASSWORD': 'Ramesh@5611',     # Replace with your password
        'HOST': 'localhost',                # Or your DB server hostname/IP
        'PORT': '5432',                     # Default PostgreSQL port
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
      'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],                      }

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
]


# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')


AUTH_USER_MODEL = 'account.CustomUser'




# Static file settings
STATIC_URL = '/static/'  # URL to access static files
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # Location of static files
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # For collecting static files during deployment
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

LOGIN_REDIRECT_URL = '/'
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# settings.py
WEB3_PROVIDER_URI = "http://localhost:7545"  # Ganache
CONTRACT_ARTIFACT_PATH = os.path.join(BASE_DIR, '../../freelancefusionsmartcontract/build/contracts/FreelanceContract.json')
DEPLOYER_ADDRESS = "0x053c480541269ceb4d557366ea3A4e9189e291c4"
DEPLOYER_PRIVATE_KEY = "0x07cc5e1518ec2287ae5424049b38cbd0d2e84bae31282406a86fc696cbe5d71d"
WEB3_CHAIN_ID = 1337  # Ganache default
KHALTI_SECRET_KEY = "key live_secret_key_68791341fdd94846a146f0457ff7b455"
KHALTI_VERIFY_URL = "https://khalti.com/api/v2/payment/verify/"




# Admin Material Dashboard specific settings
MATERIAL_ADMIN_SITE = {
    # Branding & Appearance
    'HEADER': 'Your Company Admin',  # Admin site header
    'TITLE': 'Your Company Administration',  # Admin site title
    'FAVICON': 'img/favicon.png',  # Path from static files
    'LOGO': 'img/admin-logo.png',  # Main admin logo
    'LOGIN_LOGO': 'img/login-logo.png',  # Login screen logo (400x400px)
    'LOGOUT_BG': 'img/logout-bg.jpg',  # Logout background image
    
    # Color Scheme
    'MAIN_BG_COLOR': '#2a3042',  # Primary background color
    'MAIN_HOVER_COLOR': '#1a1f2d',  # Hover state color
    'NAVBAR_COLOR': '#1a1f2d',  # Navigation bar color
    'SIDEBAR_COLOR': '#2a3042',  # Sidebar background color
    'BUTTON_COLOR': '#4CAF50',  # Primary action button color
    'ACCENT_COLOR': '#FF4081',  # Highlight color for important elements
    'ALERT_COLOR': '#F44336',  # Warning/alert color
    
    # Layout Customization
    'SHOW_THEMES': True,  # Enable theme switcher
    'TRAY_REVERSE': True,  # Reverse side tray position
    'NAVBAR_REVERSE': True,  # Reverse navbar position
    'FIXED_HEADER': True,  # Fixed position header
    'FIXED_SIDEBAR': True,  # Fixed position sidebar
    'BOXED_LAYOUT': False,  # Boxed page layout
    'COLLAPSE_SIDEBAR': True,  # Collapsible sidebar
    'MENU_ICON_COLLECTION': 'material-icons',  # Icon library
    
    # Content Display
    'SHOW_COUNTS': True,  # Show model counts
    'LIST_PER_PAGE': 25,  # Items per page in list views
    'MAX_ACTION_BUTTONS': 3,  # Max buttons in action row
    'CHART_REFRESH': 300,  # Dashboard chart refresh rate (seconds)
    
    # User Interface
    'PROFILE_PICTURE': 'img/admin-avatar.png',  # Admin avatar
    'PROFILE_BG': 'img/profile-bg.jpg',  # Profile background
    'SHOW_MENU_ICONS': True,  # Show icons in side menu
    'MENU_HOVER': 'dark',  # Menu hover style (light/dark)
    'MENU_OPEN_ON_HOVER': True,  # Open submenus on hover
    'MENU_SEARCH': True,  # Enable menu search
    
    # Custom Components
    'CUSTOM_LINKS': [
        {
            'name': 'Company Dashboard',
            'url': '/dashboard/',
            'icon': 'dashboard',
            'permissions': ['auth.view_user']
        },
        {
            'name': 'Support Center',
            'url': 'https://support.example.com',
            'icon': 'help',
            'new_window': True
        }
    ],
    
    # Advanced Configuration
    'THEME_PATH': 'admin/css/themes/',  # Custom themes directory
    'EXTRA_HEADERS': {
        'X-Frame-Options': 'SAMEORIGIN',
        'Content-Security-Policy': "default-src 'self'"
    },
    
    # Notification System
    'NOTIFICATIONS': {
        'ENABLED': True,
        'POLLING': 60,  # Seconds between checks
        'MAX_COUNT': 10,  # Max notifications to show
        'STORAGE': 'local'  # local/session/database
    },
    
    # Branding Visibility
    'FOOTER_BRANDING': True,  # Show "Powered by" footer
    'COPYRIGHT_TEXT': '© 2024 Your Company. All rights reserved.',
    
    # Security Features
    'MASK_CREDENTIALS': True,  # Mask sensitive fields
    'SESSION_TIMEOUT': 3600,  # Inactivity timeout (seconds)
    'PASSWORD_STRENGTH': 3,  # 1-4 (Minimum password strength)
}