# Generated by Django 5.1.6 on 2025-02-20 19:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_alter_project_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('proposal_text', models.TextField()),
                ('attachments', models.FileField(blank=True, null=True, upload_to='application_attachments/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('reviewing', 'Under Review')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_completion_time', models.PositiveIntegerField(blank=True, help_text='Estimated completion time in days.', null=True)),
                ('freelancer_rating', models.FloatField(blank=True, help_text="Rating out of 5 for the freelancer's work.", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('employer_feedback', models.TextField(blank=True, help_text='Feedback from the employer.', null=True)),
                ('is_shortlisted', models.BooleanField(default=False)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'freelancer')},
            },
        ),
    ]
